import React, { useState } from 'react';
import { Sparkles, Loader2, AlertCircle, Zap } from 'lucide-react';
import { aiService } from '../../../services/ai.service';
import type { PageLayout } from '../../../core/types/layout.types';

interface AiGeneratePanelProps {
  portfolioId: string;
  pageId: string;
  onLayoutGenerated: (layout: PageLayout) => void;
}

const EXAMPLE_PROMPTS = [
  'Full stack developer portfolio with hero, about, skills (React, Node.js, Python), projects grid, and contact form',
  'UX/UI designer portfolio with creative hero section, about me, design skills, portfolio showcase, and contact',
  'Data scientist portfolio with professional hero, technical skills (Python, TensorFlow, SQL), projects with GitHub links, and contact',
  'Freelance developer with experience timeline, education, projects, and social links',
];

export const AiGeneratePanel: React.FC<AiGeneratePanelProps> = ({
  portfolioId,
  pageId,
  onLayoutGenerated,
}) => {
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastSectionsCount, setLastSectionsCount] = useState<number | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim() || prompt.trim().length < 10) {
      setError('Prompt must be at least 10 characters');
      return;
    }
    setIsLoading(true);
    setError(null);
    setLastSectionsCount(null);
    try {
      const result = await aiService.generateLayout(prompt, portfolioId, pageId);
      onLayoutGenerated(result.layout);
      setLastSectionsCount(result.sectionsGenerated);
      setPrompt('');
    } catch (err: unknown) {
      const msg =
        (err as { response?: { data?: { message?: string } } })?.response?.data
          ?.message ?? 'Generation failed — please try again';
      setError(Array.isArray(msg) ? msg[0] : msg);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <div className="w-7 h-7 rounded-lg bg-violet-500/15 flex items-center justify-center">
          <Sparkles size={14} className="text-violet-400" />
        </div>
        <div>
          <p className="text-sm font-semibold text-white">AI Layout Generator</p>
          <p className="text-xs text-slate-500">Powered by Google Gemini</p>
        </div>
      </div>

      {/* Prompt textarea */}
      <textarea
        value={prompt}
        onChange={(e) => { setPrompt(e.target.value); setError(null); }}
        placeholder="e.g. Portfolio for a React developer named John with dark theme. Include about, skills section with React and Node.js, 3 projects with GitHub links, and a contact form with social links."
        rows={4}
        className="w-full px-3 py-3 rounded-xl bg-white/5 border border-white/10 text-slate-300 text-sm placeholder-slate-600 focus:outline-none focus:border-violet-500/50 resize-none transition-colors leading-relaxed"
      />

      {/* Character count */}
      <div className="flex items-center justify-between text-xs text-slate-600">
        <span>{prompt.length}/2000</span>
        <span className={prompt.length < 10 ? 'text-slate-600' : 'text-emerald-500'}>
          {prompt.length < 10 ? `${10 - prompt.length} more chars needed` : '✓ Ready'}
        </span>
      </div>

      {/* Example prompts */}
      <div className="space-y-1.5">
        <p className="text-xs text-slate-600">Try an example:</p>
        {EXAMPLE_PROMPTS.map((ex, i) => (
          <button
            key={i}
            onClick={() => setPrompt(ex)}
            className="w-full text-left text-xs text-slate-500 hover:text-indigo-400 py-1 px-2 rounded-lg hover:bg-indigo-500/10 transition-all line-clamp-1"
          >
            ↗ {ex}
          </button>
        ))}
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-start gap-2 px-3 py-2.5 rounded-lg bg-red-500/10 border border-red-500/20">
          <AlertCircle size={14} className="text-red-400 mt-0.5 shrink-0" />
          <p className="text-xs text-red-400">{error}</p>
        </div>
      )}

      {/* Success feedback */}
      {lastSectionsCount !== null && (
        <div className="flex items-center gap-2 px-3 py-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
          <Zap size={14} className="text-emerald-400 shrink-0" />
          <p className="text-xs text-emerald-400 font-semibold">
            ✓ {lastSectionsCount} sections generated by Gemini
          </p>
        </div>
      )}

      {/* Generate button */}
      <button
        onClick={handleGenerate}
        disabled={isLoading || prompt.trim().length < 10}
        className="w-full flex items-center justify-center gap-2 py-3 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 text-white font-semibold text-sm hover:shadow-lg hover:shadow-violet-500/30 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed hover:scale-[1.02]"
      >
        {isLoading ? (
          <><Loader2 size={16} className="animate-spin" /> Generating...</>
        ) : (
          <><Sparkles size={16} /> Generate Layout</>
        )}
      </button>

      <p className="text-xs text-slate-600 text-center">
        ⚠ This will replace the current layout
      </p>
    </div>
  );
};
