import { ComponentCategory } from '../schemas/component.schema';

/**
 * Built-in Component Registry — Block-only architecture.
 *
 * All old monolithic Section components (hero, about, skills, projects,
 * experience, education, contact, footer) have been removed.
 *
 * Portfolios are now built by composing these blocks using the Template Library.
 * Every block is inline-editable via data-cms-field attributes.
 */
export const BUILT_IN_COMPONENTS = [
  // ─── Navigation ───────────────────────────────────────────────────────────
  {
    type: 'navbar',
    name: 'Navigation Bar',
    description: 'Sticky top navigation block with logo, links, and optional CTA button',
    category: ComponentCategory.NAVIGATION,
    version: '2.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        logo: { type: 'string' },
        links: {
          type: 'array',
          items: {
            type: 'object',
            properties: { label: { type: 'string' }, href: { type: 'string' } },
            required: ['label', 'href'],
          },
        },
        ctaLabel: { type: 'string' },
        ctaHref: { type: 'string' },
        sticky: { type: 'boolean' },
        transparent: { type: 'boolean' },
      },
      required: ['logo'],
    },
    defaultProps: {
      logo: 'My Portfolio',
      links: [
        { label: 'About', href: '#about' },
        { label: 'Projects', href: '#projects' },
        { label: 'Contact', href: '#contact' },
      ],
      ctaLabel: 'Hire Me',
      ctaHref: '#contact',
      sticky: true,
      transparent: false,
    },
  },

  // ─── Layout Containers ────────────────────────────────────────────────────
  {
    type: 'section-wrapper',
    name: 'Section Wrapper',
    description: 'Full-width section container with optional title, subtitle, and background',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        label: { type: 'string' },
        title: { type: 'string' },
        subtitle: { type: 'string' },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
        padding: { type: 'string', enum: ['sm', 'md', 'lg', 'xl'] },
        background: { type: 'string', enum: ['default', 'alternate', 'dark', 'gradient', 'none'] },
        maxWidth: { type: 'string', enum: ['sm', 'md', 'lg', 'xl', 'full'] },
        showDivider: { type: 'boolean' },
      },
    },
    defaultProps: { align: 'center', padding: 'lg', background: 'default', maxWidth: 'xl' },
  },
  {
    type: 'columns',
    name: 'Columns',
    description: 'Side-by-side column grid layout',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        columns: { type: 'string', enum: ['2', '3', '4'] },
        gap: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl'] },
        align: { type: 'string', enum: ['start', 'center', 'end', 'stretch'] },
      },
    },
    defaultProps: { columns: '3', gap: 'md', align: 'start' },
  },
  {
    type: '_column',
    name: 'Column Slot',
    description: 'Internal column slot (used inside Columns block)',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: { type: 'object', properties: { align: { type: 'string' }, gap: { type: 'string' } } },
    defaultProps: {},
  },
  {
    type: 'row',
    name: 'Row',
    description: 'Vertical stack of blocks',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        gap: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl'] },
        align: { type: 'string', enum: ['start', 'center', 'end', 'stretch'] },
        padding: { type: 'string', enum: ['none', 'sm', 'md', 'lg'] },
      },
    },
    defaultProps: { gap: 'md', align: 'stretch', padding: 'none' },
  },
  {
    type: 'split',
    name: 'Split Layout',
    description: 'Two-column split layout with configurable width ratio',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        leftWidth: { type: 'string', enum: ['33', '40', '50', '60', '67'] },
        verticalAlign: { type: 'string', enum: ['start', 'center', 'end'] },
        gap: { type: 'string', enum: ['sm', 'md', 'lg', 'xl'] },
        reverse: { type: 'boolean' },
      },
    },
    defaultProps: { leftWidth: '50', verticalAlign: 'center', gap: 'lg', reverse: false },
  },
  {
    type: 'card',
    name: 'Card',
    description: 'Styled card container for grouped content',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        variant: { type: 'string', enum: ['default', 'glass', 'outlined', 'elevated', 'gradient'] },
        padding: { type: 'string', enum: ['none', 'sm', 'md', 'lg'] },
        radius: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl', '2xl'] },
        showHeader: { type: 'boolean' },
        title: { type: 'string' },
        subtitle: { type: 'string' },
      },
    },
    defaultProps: { variant: 'glass', padding: 'md', radius: 'xl', showHeader: false },
  },
  {
    type: 'container',
    name: 'Container',
    description: 'Generic box container for grouping blocks',
    category: ComponentCategory.LAYOUT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        padding: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl'] },
        style: { type: 'string', enum: ['card', 'glass', 'outlined', 'filled', 'none'] },
        maxWidth: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl', '2xl'] },
      },
    },
    defaultProps: { padding: 'md', style: 'card', maxWidth: 'none' },
  },

  // ─── Atomic Blocks ────────────────────────────────────────────────────────
  {
    type: 'heading',
    name: 'Heading',
    description: 'Title or heading text with size and alignment options',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        text: { type: 'string' },
        level: { type: 'string', enum: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] },
        size: { type: 'string', enum: ['sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
        gradient: { type: 'boolean' },
      },
      required: ['text'],
    },
    defaultProps: { text: 'Heading', level: 'h2', size: 'xl', align: 'left', gradient: false },
  },
  {
    type: 'text',
    name: 'Text / Paragraph',
    description: 'Body text or paragraph content',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        content: { type: 'string' },
        size: { type: 'string', enum: ['sm', 'base', 'lg', 'xl'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
        muted: { type: 'boolean' },
      },
      required: ['content'],
    },
    defaultProps: { content: 'Your text here', size: 'base', align: 'left', muted: false },
  },
  {
    type: 'button',
    name: 'Button',
    description: 'Call-to-action button with customizable style',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        label: { type: 'string' },
        href: { type: 'string' },
        variant: { type: 'string', enum: ['primary', 'secondary', 'ghost', 'danger'] },
        size: { type: 'string', enum: ['sm', 'md', 'lg'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
      },
      required: ['label'],
    },
    defaultProps: { label: 'Click Me', href: '#', variant: 'primary', size: 'md', align: 'left' },
  },
  {
    type: 'badge',
    name: 'Badge / Tag',
    description: 'Small colored badge or label',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        label: { type: 'string' },
        variant: { type: 'string', enum: ['indigo', 'violet', 'emerald', 'amber', 'rose', 'sky', 'slate'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
        dot: { type: 'boolean' },
      },
      required: ['label'],
    },
    defaultProps: { label: 'New', variant: 'indigo', align: 'left' },
  },
  {
    type: 'image',
    name: 'Image',
    description: 'Image with optional caption and styling',
    category: ComponentCategory.MEDIA,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        src: { type: 'string', format: 'uri' },
        alt: { type: 'string' },
        caption: { type: 'string' },
        width: { type: 'string' },
        borderRadius: { type: 'string', enum: ['none', 'sm', 'md', 'lg', 'xl', '2xl', 'full'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
      },
    },
    defaultProps: { src: '', alt: 'Image', width: '100%', borderRadius: 'lg', align: 'center' },
  },
  {
    type: 'stat',
    name: 'Stat / Counter',
    description: 'Key metric display: value + label + icon',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        value: { type: 'string' },
        label: { type: 'string' },
        description: { type: 'string' },
        icon: { type: 'string' },
        variant: { type: 'string', enum: ['default', 'card', 'bordered', 'minimal'] },
        accent: { type: 'string', enum: ['indigo', 'violet', 'emerald', 'amber', 'rose', 'sky'] },
        align: { type: 'string', enum: ['left', 'center', 'right'] },
      },
      required: ['value', 'label'],
    },
    defaultProps: { value: '5+', label: 'Years Experience', icon: '🏆', variant: 'card', accent: 'indigo', align: 'center' },
  },
  {
    type: 'feature-card',
    name: 'Feature Card',
    description: 'Icon + title + description card for features, services, or skills',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        icon: { type: 'string' },
        title: { type: 'string' },
        description: { type: 'string' },
        variant: { type: 'string', enum: ['default', 'glass', 'outlined', 'gradient', 'minimal'] },
        iconPosition: { type: 'string', enum: ['top', 'left'] },
        accent: { type: 'string', enum: ['indigo', 'violet', 'emerald', 'amber', 'rose', 'sky'] },
        href: { type: 'string' },
        linkLabel: { type: 'string' },
      },
      required: ['title'],
    },
    defaultProps: { icon: '✨', title: 'Feature Title', description: 'Feature description', variant: 'glass', iconPosition: 'top', accent: 'indigo' },
  },
  {
    type: 'timeline-item',
    name: 'Timeline Item',
    description: 'Experience/education entry with role, company, dates, and achievements',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        role: { type: 'string' },
        company: { type: 'string' },
        startDate: { type: 'string' },
        endDate: { type: 'string' },
        location: { type: 'string' },
        description: { type: 'string' },
        highlights: {
          type: 'array',
          items: {
            type: 'object',
            properties: { value: { type: 'string' } },
          },
        },
        variant: { type: 'string', enum: ['card', 'minimal'] },
        accent: { type: 'string', enum: ['indigo', 'violet', 'emerald', 'amber', 'rose'] },
        showDot: { type: 'boolean' },
      },
      required: ['role', 'company'],
    },
    defaultProps: { role: 'Developer', company: 'Company', startDate: '2022', endDate: 'Present', variant: 'card', accent: 'indigo', showDot: true },
  },
  {
    type: 'divider',
    name: 'Divider',
    description: 'Horizontal dividing line',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: {
        style: { type: 'string', enum: ['solid', 'dashed', 'dotted', 'gradient'] },
        spacing: { type: 'string', enum: ['sm', 'md', 'lg', 'xl'] },
      },
    },
    defaultProps: { style: 'solid', spacing: 'md' },
  },
  {
    type: 'spacer',
    name: 'Spacer',
    description: 'Vertical spacing block',
    category: ComponentCategory.CONTENT,
    version: '1.0.0',
    isBuiltIn: true,
    schema: {
      type: 'object',
      properties: { height: { type: 'string', enum: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'] } },
    },
    defaultProps: { height: 'md' },
  },
];
