name: Build, Test and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ] # Trigger

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .
        
      - name: Run Tests
        run: |
          docker run \
            -e PORT=3000 \
            -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e JWT_EXPIRES_IN="7d" \
            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            -e GEMINI_MODEL="gemini-2.5-flash" \
            my-app:${{ github.sha }} 

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Push Image to Artifact Registry
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          docker tag my-app:${{ github.sha }} $IMAGE_PATH
          docker push $IMAGE_PATH

      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_PATH \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars="MONGODB_URI=${{ secrets.MONGODB_URI }}" \
            --set-env-vars="JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars="GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
            --set-env-vars="GEMINI_MODEL=gemini-2.5-flash"